# Generated by Django 4.1.3 on 2022-11-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_price_par_unit_product_price_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionstep',
            name='title',
        ),
        migrations.AddField(
            model_name='productionstep',
            name='step',
            field=models.CharField(choices=[('FIRST_STEP', 'First Step'), ('SECOND_STEP', 'Second Step'), ('THIRD_STEP', 'Third Step'), ('FOURTH_STEP', 'Fourth Step')], default='', max_length=200),
            preserve_default=False,
        ),
    ]
