# Generated by Django 4.1.3 on 2022-11-27 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_full_description_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstep',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_steps', to='product.product'),
        ),
    ]
