# Generated by Django 4.1.3 on 2023-01-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_subcategory_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_price_per_unit',
            field=models.FloatField(default=0, help_text='Unit price', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('UNPUBLISH', 'UnPublish'), ('PUBLISH', 'Publish')], default='UNPUBLISH', max_length=20),
        ),
    ]
