# Generated by Django 4.1.3 on 2023-01-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_sell_price_per_unit_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='possible_delivery_date',
            field=models.DateField(blank=True, help_text='Possible delivery date', null=True),
        ),
    ]
