# Generated by Django 4.1.3 on 2023-05-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_sell_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
