# Generated by Django 4.1.3 on 2022-11-27 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_terms_and_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFarmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_farmer', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmer_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Farmer',
                'verbose_name_plural': 'Agent Farmers',
                'db_table': 'agent_farmers',
            },
        ),
    ]
