# Generated by Django 4.1.3 on 2022-11-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('AGENT', 'Agent'), ('CUSTOMER', 'Customer')], max_length=50, null=True),
        ),
    ]
