# Generated by Django 4.1.3 on 2022-12-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_otpmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
