# Generated by Django 4.1.3 on 2023-02-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('FARMER', 'Farmer'), ('AGENT', 'Agent'), ('CUSTOMER', 'Customer'), ('ADMIN', 'Admin')], max_length=50, null=True),
        ),
    ]
