# Generated by Django 4.1.3 on 2023-03-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid_back',
            field=models.ImageField(blank=True, null=True, upload_to='images/user'),
        ),
        migrations.AddField(
            model_name='user',
            name='nid_front',
            field=models.ImageField(blank=True, null=True, upload_to='images/user'),
        ),
    ]
