# Generated by Django 4.1.3 on 2023-03-16 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_district_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='division_user', to='user.division'),
        ),
    ]
