# Generated by Django 4.1.3 on 2023-03-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_nid_back_user_nid_front'),
        ('user', '0014_alter_user_division'),
    ]

    operations = [
    ]
