# Generated by Django 4.1.3 on 2023-03-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_merge_20230319_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='english_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
