# Generated by Django 4.1.3 on 2023-01-15 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=15)),
                ('coupon_title', models.CharField(max_length=255)),
                ('min_shopping', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, help_text='Amount Coupon', max_length=255, null=True)),
                ('number_of_uses', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_name', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PaymentType',
                'verbose_name_plural': 'PaymentTypes',
                'db_table': 'payment_types',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vat', models.FloatField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.SlugField(allow_unicode=True)),
                ('product_count', models.IntegerField(blank=True, null=True)),
                ('total_price', models.FloatField(default=0, max_length=255)),
                ('refund', models.BooleanField(default=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('coupon_discount_amount', models.FloatField(blank=True, max_length=255, null=True)),
                ('coupon_status', models.BooleanField(default=False)),
                ('vat_amount', models.FloatField(blank=True, max_length=255, null=True)),
                ('vat_percentage', models.FloatField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('DUE', 'Due'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='Paid', max_length=20)),
                ('cash_on_delivery', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('ON_PROCESS', 'On Process'), ('CANCELED', 'Canceled'), ('ON_TRANSIT', 'On Transit'), ('DELIVERED', 'Delivered')], default='Canceled', max_length=20)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.coupon')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.deliveryaddress')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_farmer', to=settings.AUTH_USER_MODEL)),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.paymenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
