# Generated by Django 4.1.3 on 2023-01-17 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_product_possible_delivery_date'),
        ('order', '0002_coupon_paymenttype_setting_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CouponStat',
                'verbose_name_plural': 'CouponStats',
                'db_table': 'coupon_stats',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.FloatField(default=0, max_length=255)),
                ('total_price', models.FloatField(default=0, max_length=255)),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
                'db_table': 'order_items',
            },
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='number_of_uses',
            new_name='max_time',
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ON_PROCESS', 'On Process'), ('CANCELED', 'Canceled'), ('ON_TRANSIT', 'On Transit'), ('DELIVERED', 'Delivered')], default='ON_PROCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('DUE', 'Due'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='DUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('DUE', 'Due'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='COD', max_length=20),
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_order', to='order.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='couponstat',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='order.coupon'),
        ),
        migrations.AddField(
            model_name='couponstat',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_stat_order', to='order.order'),
        ),
        migrations.AddField(
            model_name='couponstat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
