# Generated by Django 4.1.3 on 2023-02-07 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0011_alter_user_phone_number'),
        ('order', '0003_couponstat_orderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.division')),
                ('upazilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.upazilla')),
            ],
            options={
                'verbose_name': 'PickupLocation',
                'verbose_name_plural': 'PickupLocations',
                'db_table': 'pickup_locations',
            },
        ),
        migrations.CreateModel(
            name='AgentPickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_location_agent', to='order.pickuplocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_pickup_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AgentPickupLocation',
                'verbose_name_plural': 'AgentPickupLocations',
                'db_table': 'agent_pickup_locations',
            },
        ),
    ]
