# Generated by Django 4.1.3 on 2023-02-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_pickuplocation_agentpickuplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_qc_passed',
            field=models.BooleanField(default=False),
        ),
    ]
