# Generated by Django 4.1.3 on 2023-02-14 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0007_order_pickup_request_alter_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('BANK_ACCOUNT', 'Bank Account'), ('MFS', 'Mobile Financial Services')], max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brunch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mobile_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_account_info', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmer_account_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer Account Info',
                'verbose_name_plural': 'Farmer Account Info',
                'db_table': 'farmer_account_info',
            },
        ),
    ]
