# Generated by Django 4.1.3 on 2023-02-15 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0008_farmeraccountinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suborder_id', models.SlugField(allow_unicode=True)),
                ('product_count', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('refund', models.BooleanField(default=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('coupon_discount_amount', models.FloatField(blank=True, max_length=255, null=True)),
                ('coupon_status', models.BooleanField(default=False)),
                ('vat_amount', models.FloatField(blank=True, max_length=255, null=True)),
                ('vat_percentage', models.FloatField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('DUE', 'Due'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='DUE', max_length=20)),
                ('payment_type', models.CharField(choices=[('DUE', 'Due'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='COD', max_length=20)),
                ('cash_on_delivery', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('ON_PROCESS', 'On Process'), ('CANCELED', 'Canceled'), ('ON_TRANSIT', 'On Transit'), ('DELIVERED', 'Delivered')], default='ON_PROCESS', max_length=20)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_qc_passed', models.BooleanField(default=False)),
                ('pickup_request', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.coupon')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.deliveryaddress')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suborder_farmer', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_suborder', to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suborder_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub Order',
                'verbose_name_plural': 'Sub Orders',
                'db_table': 'sub_orders',
            },
        ),
    ]
