# Generated by Django 4.1.3 on 2023-02-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_suborder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suborder',
            old_name='suborder_id',
            new_name='suborder_number',
        ),
    ]
