# Generated by Django 4.1.3 on 2023-03-01 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_user_type'),
        ('order', '0011_orderitem_suborder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='city',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='upazilla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.upazilla'),
            preserve_default=False,
        ),
    ]
