# Generated by Django 4.1.3 on 2023-03-02 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderitem_suborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.agentpickuplocation'),
        ),
    ]
