# Generated by Django 4.1.3 on 2023-03-02 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_agentpickuplocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_qc_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_pickup_location', to='order.agentpickuplocation'),
        ),
    ]
