# Generated by Django 4.1.3 on 2023-03-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderitem_is_qc_passed_orderitem_pickup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborder',
            name='pickup_location',
        ),
    ]
