# Generated by Django 4.1.3 on 2023-03-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_deliveryaddress_city_deliveryaddress_district_and_more'),
        ('order', '0015_remove_suborder_pickup_location'),
    ]

    operations = [
    ]
