# Generated by Django 4.1.3 on 2023-03-05 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0016_merge_20230305_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmeraccountinfo',
            name='account_type',
            field=models.CharField(blank=True, choices=[('BANK_ACCOUNT', 'Bank Account'), ('MFS', 'Mobile Financial Services')], max_length=20, null=True),
        ),
    ]
