# Generated by Django 4.1.3 on 2023-03-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_orderitem_agent_alter_farmeraccountinfo_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_qc_passed',
            field=models.BooleanField(default='NEUTRAL'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_qc_passed',
            field=models.BooleanField(default='NEUTRAL'),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='is_qc_passed',
            field=models.BooleanField(default='NEUTRAL'),
        ),
    ]
