# Generated by Django 4.1.3 on 2023-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_is_qc_passed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_qc_passed',
            field=models.CharField(choices=[('NEUTRAL', 'Neutral'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='NEUTRAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_qc_passed',
            field=models.CharField(choices=[('NEUTRAL', 'Neutral'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='NEUTRAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='is_qc_passed',
            field=models.CharField(choices=[('NEUTRAL', 'Neutral'), ('PASS', 'Pass'), ('FAIL', 'Fail')], default='NEUTRAL', max_length=20),
        ),
    ]
