# Generated by Django 4.1.3 on 2023-03-05 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_is_qc_passed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_pickup_location', to='order.pickuplocation'),
        ),
    ]
