# Generated by Django 4.1.3 on 2023-03-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_merge_20230305_0742'),
        ('order', '0019_alter_order_is_qc_passed_and_more'),
    ]

    operations = [
    ]
