# Generated by Django 4.1.3 on 2023-03-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_orderitem_pickup_location'),
        ('order', '0020_merge_20230305_0948'),
    ]

    operations = [
    ]
