# Generated by Django 4.1.3 on 2023-03-06 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0022_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='farmer',
            field=models.ForeignKey(default=124, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
