# Generated by Django 4.1.3 on 2023-03-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_paymenthistory_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('DUE', 'Due'), ('PAID', 'Paid'), ('NONE', 'None')], default='DUE', max_length=20),
        ),
    ]
