# Generated by Django 4.1.3 on 2023-03-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_orderitem_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('NONE', 'None'), ('DUE', 'Due'), ('PAID', 'Paid')], default='NONE', max_length=20),
        ),
    ]
