# Generated by Django 4.1.3 on 2023-03-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_orderitem_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('PG', 'Payment Gateway')], default='COD', max_length=20),
        ),
    ]
