# Generated by Django 4.1.3 on 2023-05-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_suborder_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='delivery_charge',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
