# Generated by Django 4.1.3 on 2023-05-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_setting_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='delivery_charge',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
