# Generated by Django 4.1.3 on 2023-05-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_suborder_divided_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmeraccountinfo',
            name='account_type',
            field=models.CharField(blank=True, choices=[('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('ROCKET', 'Rocket'), ('UPAY', 'Upay'), ('BANK_ACCOUNT', 'Bank Account')], max_length=20, null=True),
        ),
    ]
