# Generated by Django 4.1.3 on 2023-06-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_orderitem_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='commission_total',
            field=models.FloatField(default=0, help_text='Agent Commission Total = commission x product quantity', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='commission',
            field=models.FloatField(default=0, help_text='Agent Commission Amount', max_length=255),
        ),
    ]
