name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install openssh-client -y

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 165.232.171.7 >> ~/.ssh/known_hosts

    - name: Deploy to DigitalOcean
      run: |
        rsync -r --quiet --delete . root@165.232.171.7:/home/armanbhaiapi.mwebservices.co/ArmanBhai/code

    - name: Install Python and dependencies
      run: |
        ssh root@165.232.171.7 'sudo apt-get update'
        ssh root@165.232.171.7 'cd /home/armanbhaiapi.mwebservices.co/ArmanBhai/code && source ../sklenv/bin/activate && pip install -r requirements.txt'

    - name: Migrate database
      run: |
        ssh root@165.232.171.7 'cd /home/armanbhaiapi.mwebservices.co/ArmanBhai/code && source ../sklenv/bin/activate && python manage.py migrate'

    - name: Restart Django application
      run: |
        ssh root@165.232.171.7 'sudo systemctl restart apache2'

